// AUTOGENERATED BY COPILOT COMPLETELY
// TODO: redo

#include "utils.h"

BOOL SetClipboardText(const char* text) {
    if (!OpenClipboard(NULL))
        return FALSE;

    if (!EmptyClipboard()) {
        CloseClipboard();
        return FALSE;
    }

    int wlen = MultiByteToWideChar(CP_UTF8, 0, text, -1, NULL, 0);
    if (wlen == 0) {
        CloseClipboard();
        return FALSE;
    }

    HGLOBAL hMem = GlobalAlloc(GMEM_MOVEABLE, wlen * sizeof(wchar_t));
    if (!hMem) {
        CloseClipboard();
        return FALSE;
    }

    wchar_t* wbuf = (wchar_t*)GlobalLock(hMem);
    MultiByteToWideChar(CP_UTF8, 0, text, -1, wbuf, wlen);
    GlobalUnlock(hMem);

    SetClipboardData(CF_UNICODETEXT, hMem);
    CloseClipboard();
    return TRUE;
}

char* GetClipboardText() {
    if (!OpenClipboard(NULL)) {
        return NULL;
    }

    HANDLE hData = GetClipboardData(CF_UNICODETEXT);
    if (hData == NULL) {
        CloseClipboard();
        return NULL;
    }

    wchar_t* pszText = (wchar_t*)GlobalLock(hData);
    if (pszText == NULL) {
        CloseClipboard();
        return NULL;
    }

    int len = WideCharToMultiByte(CP_UTF8, 0, pszText, -1, NULL, 0, NULL, NULL);
    char* pszTextUTF8 = (char*)malloc(len);
    if (pszTextUTF8) {
        WideCharToMultiByte(CP_UTF8, 0, pszText, -1, pszTextUTF8, len, NULL, NULL);
    }

    GlobalUnlock(hData);
    CloseClipboard();

    return pszTextUTF8;
}
